import {
  Moon,
  SunMedium,
  LucideIcon,
  Loader2,
  ChevronLeft,
  TableProperties,
  Building2,
  ChevronsUpDown,
  Edit,
  Eye,
  Trash2,
  Laptop,
  Palette,
  LayoutDashboard,
  PlusCircle,
  Settings,
  ArrowLeft,
  CheckCircle2,
  Circle,
  Copy,
  HelpCircle,
  Info,
  ShieldAlert,
  Timer,
  XCircle,
  Check,
  LogOut,
  ChevronsLeft,
  ChevronRight,
  ChevronsRight,
  SlidersHorizontal,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  previous: ChevronLeft,
  speedPrevious: ChevronsLeft,
  next: ChevronRight,
  speedNext: ChevronsRight,
  options: SlidersHorizontal,
  sun: SunMedium,
  moon: Moon,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  table: TableProperties,
  sort: ChevronsUpDown,
  org: Building2,
  view: Eye,
  edit: Edit,
  delete: Trash2,
  system: Laptop,
  theme: Palette,
  settings: Settings,
  dashboard: LayoutDashboard,
  plus: PlusCircle,
  copy: Copy,
  left: ArrowLeft,
  shield: ShieldAlert,
  info: Info,
  checked: CheckCircle2,
  cancel: XCircle,
  pending: Timer,
  circle: Circle,
  question: HelpCircle,
  check: Check,
  logout: LogOut,
};
